version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d

    ports:
      - '8080:80'
    depends_on:
      - appcore
    networks:
      - nginx_network
  
  appcore:
    build: ./AppCore
    container_name: appcore
    volumes:
      - ./AppCore:/AppCore
    ports:
      - 3001:3000
    expose:
      - '3000'
    tty: true
    networks:
      - nginx_network
  
networks:
  nginx_network:
    driver: bridge