services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./appcore/static:/AppCore/static
    ports:
      - '8080:80'
    depends_on:
      - appcore
    networks:
      - nginx_network
  
  appcore:
    build: ./appcore
    container_name: appcore
    volumes:
      - ./appcore:/AppCore
    ports:
      - 3001:3001
    expose:
      - '3001'
    tty: true
    networks:
      - nginx_network
  
networks:
  nginx_network:
    driver: bridge
